application: acejongbok
version: 1
runtime: php
api_version: 1

handlers:
# HTML PAGES
# ex) http://project-id.appspot.com/
- url: /index.html
  static_files: index.html
  upload: index.html
  mime_type: text/html

# ex) http://project-id.appspot.com/idea.html
- url: /idea.html
  static_files: idea.html
  upload: idea.html
  mime_type: text/html

# ex) http://project-id.appspot.com/idea.html
- url: /index2.html
  static_files: index2.html
  upload: index2.html
  mime_type: text/html

  # ex) http://project-id.appspot.com/idea.html
- url: /index3.html
  static_files: index3.html
  upload: index3.html
  mime_type: text/html

 # ex) http://project-id.appspot.com/idea.html
- url: /index4.html
  static_files: index4.html
  upload: index4.html
  mime_type: text/html

 # ex) http://project-id.appspot.com/idea.html
- url: /index5.html
  static_files: index5.html
  upload: index5.html
  mime_type: text/html


 # ex) http://project-id.appspot.com/idea.html
- url: /index6.html
  static_files: index6.html
  upload: index6.html
  mime_type: text/html


 # ex) http://project-id.appspot.com/idea.html
- url: /index7.html
  static_files: index7.html
  upload: index6.html
  mime_type: text/html
# UPLOAD STATIC FILE
- url: /css
  static_dir: css
  mime_type: text/css

- url: /js
  static_dir: js
  mime_type: text/javascript

# UPLOAD RESOURCE [img: .png | audio: .mp3 | video: .mp4]
- url: /images
  static_dir: images
  mime_type: image/png
